### PR TITLE
Fix Lit.init on Rails 6

### LINKED ISSUE #143: Rails 6 - init
Would be great to update this awesome gem for Rails 6. It works fine with 5.2. When I switch to 6, there is some problem on start:

NoMethodError (undefined method `cache' for nil:NilClass):
  
lit (1.0.2) app/controllers/lit/application_controller.rb:20:in `stop_hits_counter'
activesupport (6.0.0) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (6.0.0) lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (6.0.0) lib/active_support/callbacks.rb:202:in `block in halting'
activesupport (6.0.0) lib/active_support/callbacks.rb:514:in `block in invoke_before'
activesupport (6.0.0) lib/active_support/callbacks.rb:514:in `each'
activesupport (6.0.0) lib/active_support/callbacks.rb:514:in `invoke_before'
activesupport (6.0.0) lib/active_support/callbacks.rb:134:in `run_callbacks'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
railties (6.0.0) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.0) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.0) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.0) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
bullet (6.0.2) lib/bullet/rack.rb:12:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
simple-captcha (00cd0f349348) lib/simple_captcha/middleware.rb:47:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/cookies.rb:648:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
raygun4ruby (3.2.1) lib/raygun/middleware/rails_insert_affected_user.rb:11:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
raygun4ruby (3.2.1) lib/raygun/middleware/rack_exception_interceptor.rb:10:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
raygun4ruby (3.2.1) lib/raygun/middleware/breadcrumbs_store_initializer.rb:12:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
raygun4ruby (3.2.1) lib/raygun/middleware/javascript_exception_tracking.rb:8:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0) lib/rails/rack/logger.rb:28:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rails_autoscale_agent (0.6.3) lib/rails_autoscale_agent/middleware.rb:32:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-ssl (1.4.1) lib/rack/ssl.rb:25:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
railties (6.0.0) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.0) lib/rails/railtie.rb:190:in `method_missing'
newrelic_rpm (6.7.0.359) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
puma (4.2.1) lib/puma/configuration.rb:228:in `call'
puma (4.2.1) lib/puma/server.rb:667:in `handle_request'
puma (4.2.1) lib/puma/server.rb:470:in `process_client'
puma (4.2.1) lib/puma/server.rb:328:in `block in run'
puma (4.2.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

### PR DESCRIPTION
**Pull request by colorfulfool**
Fixes #143

For context, see https://github.com/rails/rails/issues/35329

### CODE REVIEW

**Comment by mlitwiniuk** [comment]
@colorfulfool could you update PR with rebased master? `.travis.yml` got changed. To add full Rails 6 support, we should add rails 6 gemfile (and drop rails 4.2) - will you do that or can I use your change as base for full Rails 6 support?

**Comment by colorfulfool** [comment]
Sure you can. I'm not an expert on Rails versions, I just changed what was necessary to get it to work.
